import { Metadata } from "next";
import { Montserrat } from "next/font/google";

import Footer from "../../features/footer/components/footer";
import Header from "../../features/top-header/components/main_header";
import { heveticaNeue } from "../../lib/fonts";
import { Locales } from "../../middleware";
import { getDictionary } from "./dictionaries";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ lang: Locales }>;
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { lang } = await params;
  const dict = await getDictionary(lang);
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${heveticaNeue.variable} antialiased md:min-w-[992px]`}
      >
        <Header dict={dict} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
